#!/usr/bin/env python3
"""Generate Feast FeatureViews from exported offline parquet tables.

Goal
----
You want *all* families available via Feast without hand-maintaining schemas.
This script inspects `data/feast_offline/h{horizon}/*.parquet` and writes a
`feature_definitions_auto.py` module that registers:
- Entities: symbol + split
- A FileSource per family
- A FeatureView per family with schema inferred from parquet metadata
- A FeatureService that includes all inferred FeatureViews

Typical workflow
----------------
1) Export caches -> offline tables
   python tools/feast/export_local_cache_to_feast_offline.py --horizon 63 --families all

2) Generate Feast definitions
   python tools/feast/generate_feature_definitions.py --horizon 63

3) Apply Feast repo
   (cd feature_repo/feature_repo && feast apply)
"""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, List, Optional

import pyarrow as pa
import pyarrow.parquet as pq


ENTITY_COLS = {"symbol", "split", "event_timestamp"}


def _unwrap_dictionary(t: pa.DataType) -> pa.DataType:
    if pa.types.is_dictionary(t):
        return t.value_type
    return t


def _feast_dtype_for_arrow(t: pa.DataType) -> Optional[str]:
    t = _unwrap_dictionary(t)

    if pa.types.is_float32(t) or pa.types.is_float16(t):
        return "Float32"
    if pa.types.is_float64(t):
        return "Float64"
    if pa.types.is_integer(t) or pa.types.is_unsigned_integer(t):
        return "Int64"
    if pa.types.is_boolean(t):
        return "Bool"
    if pa.types.is_string(t) or pa.types.is_large_string(t):
        return "String"

    # Skip other types by default (timestamps, structs, lists, bytes, etc.)
    return None


def _parquet_schema_fields(path: Path) -> List[tuple[str, str]]:
    pf = pq.ParquetFile(path)
    schema = pf.schema_arrow

    fields: List[tuple[str, str]] = []
    for field in schema:
        name = str(field.name)
        if name in ENTITY_COLS:
            continue
        dtype = _feast_dtype_for_arrow(field.type)
        if dtype is None:
            continue
        fields.append((name, dtype))

    # Stable ordering
    fields.sort(key=lambda x: x[0])
    return fields


def _iter_family_parquets(root: Path, horizon: int) -> Iterable[Path]:
    folder = root / f"h{int(horizon)}"
    if not folder.exists():
        return []
    return sorted(folder.glob("*.parquet"))


@dataclass(frozen=True)
class FamilyFV:
    family: str
    fields: List[tuple[str, str]]


def generate(off_root: Path, horizon: int, out_path: Path) -> None:
    parquets = list(_iter_family_parquets(off_root, horizon=horizon))
    if not parquets:
        raise SystemExit(f"No offline parquet tables found under {off_root}/h{horizon}/*.parquet")

    families: List[FamilyFV] = []
    for path in parquets:
        fam = path.stem
        fields = _parquet_schema_fields(path)
        if not fields:
            # If a family has only entities / non-supported types, skip.
            continue
        families.append(FamilyFV(family=fam, fields=fields))

    families.sort(key=lambda x: x.family)
    family_names = {f.family for f in families}

    out_path.parent.mkdir(parents=True, exist_ok=True)

    lines: List[str] = []
    lines.append(
        '"""AUTO-GENERATED by tools/feast/generate_feature_definitions.py.\n\n'
        'Do not edit manually. Re-run the generator after exporting offline tables.\n'
        '"""'
    )
    lines.append("")
    lines.append("from __future__ import annotations")
    lines.append("")
    lines.append("from datetime import timedelta")
    lines.append("")
    lines.append("from feast import Entity, FeatureService, FeatureView, Field, FileSource, ValueType")
    lines.append("from feast.types import Bool, Float32, Float64, Int64, String")
    lines.append("")
    lines.append("# Entities")
    lines.append('ticker = Entity(name="ticker", join_keys=["symbol"], value_type=ValueType.STRING)')
    lines.append('wf_split = Entity(name="wf_split", join_keys=["split"], value_type=ValueType.STRING)')
    lines.append("")

    # FileSources
    lines.append("# Offline sources")
    for fv in families:
        lines.append(
            f"{fv.family}_source = FileSource(\n"
            f"    name=\"{fv.family}_source\",\n"
            f"    path=\"../../data/feast_offline/h{int(horizon)}/{fv.family}.parquet\",\n"
            f"    timestamp_field=\"event_timestamp\",\n"
            f")"
        )
        lines.append("")

    # FeatureViews
    lines.append("# Feature views")
    lines.append("_TTL = timedelta(days=3650)")
    lines.append("")

    for fv in families:
        lines.append(f"{fv.family}_fv = FeatureView(")
        lines.append(f"    name=\"{fv.family}\",")
        lines.append("    entities=[ticker, wf_split],")
        lines.append("    ttl=_TTL,")
        lines.append("    schema=[")
        for col, dtype in fv.fields:
            lines.append(f"        Field(name=\"{col}\", dtype={dtype}),")
        lines.append("    ],")
        lines.append("    online=False,")
        lines.append(f"    source={fv.family}_source,")
        lines.append(f"    tags={{\"family\": \"{fv.family}\", \"horizon\": \"{int(horizon)}\"}},")
        lines.append(")")
        lines.append("")

    # Feature services
    lines.append("# Feature services")

    # All families currently exported for this horizon.
    service_name = f"phase2_all_h{int(horizon)}_v1"
    lines.append(f"{service_name} = FeatureService(")
    lines.append(f"    name=\"{service_name}\",")
    lines.append("    features=[")
    for fv in families:
        lines.append(f"        {fv.family}_fv,")
    lines.append("    ],")
    lines.append(")")
    lines.append("")

    # Back-compat convenience services (only emitted if all required FVs exist).
    base_chain = ["quantile_forecast", "calibration", "online_learning"]
    if all(name in family_names for name in base_chain):
        lines.append("phase2_base_v1 = FeatureService(")
        lines.append("    name=\"phase2_base_v1\",")
        lines.append("    features=[")
        for name in base_chain:
            lines.append(f"        {name}_fv,")
        lines.append("    ],")
        lines.append(")")
        lines.append("")

    hf_blocks = [
        "tech_micro_hf",
        "forecast_hf",
        "vol_deriv_hf",
        "macro_regime_hf",
        "fundamental_val_hf",
        "news_nlp_hf",
    ]
    if all(name in family_names for name in hf_blocks):
        lines.append("phase2_hf_blocks_v1 = FeatureService(")
        lines.append("    name=\"phase2_hf_blocks_v1\",")
        lines.append("    features=[")
        for name in hf_blocks:
            lines.append(f"        {name}_fv,")
        lines.append("    ],")
        lines.append(")")
        lines.append("")

    if all(name in family_names for name in (base_chain + hf_blocks)):
        lines.append("phase2_full_v1 = FeatureService(")
        lines.append("    name=\"phase2_full_v1\",")
        lines.append("    features=[")
        for name in base_chain + hf_blocks:
            lines.append(f"        {name}_fv,")
        lines.append("    ],")
        lines.append(")")
        lines.append("")

    out_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"[gen] wrote {out_path} families={len(families)}")


def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--offline-root", type=Path, default=Path("data/feast_offline"))
    p.add_argument("--horizon", type=int, required=True)
    p.add_argument(
        "--out",
        type=Path,
        default=Path("feature_repo/feature_repo/feature_definitions_auto.py"),
        help="Output python module path",
    )
    args = p.parse_args()

    generate(off_root=args.offline_root, horizon=args.horizon, out_path=args.out)


if __name__ == "__main__":
    main()
